import ResponsiveAppBar from "@/components/dashboard/ResponsiveAppBar";
import { Box } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function dashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box>
      <ResponsiveAppBar>{children}</ResponsiveAppBar>
    </Box>
  );
}
